AWSTemplateFormatVersion: "2010-09-09"
Description: Panda Sky Core Resources - Dispatcher {{name}} {{env}}
Resources:

  {{> alb }}

  {{> vpc }}

  {{> iamrole }}

  {{> cuddle-monkey }}

  {{> lambda }}

  {{> edge }}

{{#if vpc}}
Outputs:
  VPC:
    Value: !Ref VPC

  Subnets:
    Value: !Join
      - ","
      - - !Ref Subnet1
        - !Ref Subnet2

  AvailabilityZones:
    Value: !Join
      - ","
      - - !GetAtt [ Subnet1, AvailabilityZone ]
        - !GetAtt [ Subnet2, AvailabilityZone ]

  SecurityGroups:
    Value: !Join
      - ","
      - - !Ref SecurityGroup

  RouteTables:
    Value: !Join
      - ","
      - - !Ref RouteTable
{{/if}}
