AWSTemplateFormatVersion: "2010-09-09"
Description: Panda Sky Partition
Resources:
  {{#if aws.vpc}}
  {{> vpc }}
  Parameters:
    SecurityGroups:
      Type: String
      Description: comma delimited list of security groups for the core stack VPC
    Subnets:
      Type: String
      Description: comma delimited list of subnet IDs for the core stack VPC
  {{/if}}

  # IAM (Identity and Access Management), granting functions acccess to other stack resources.
  {{> iamrole}}

  {{#with rootResource}}
  # The root resource needs different expansion than others. Define all the Lambdas for methods on the root resource.
  {{#each methods}}
  {{> lambda }}
  {{/each}}
  {{/with}}

  # Define all Lambdas for methods on all non-root resources
  {{#each resources}}
  {{#each methods}}
  {{> lambda }}
  {{/each}}
  {{/each}}

  {{#with rootResource}}
  # The root resource needs different expansion than others. Define all the Lambdas for methods on the root resource.
  {{#each methods}}
  {{> lambda-permissions}}
  {{/each}}
  {{/with}}

  # Define all Lambdas for methods on all non-root resources
  {{#each resources}}
  {{#each methods}}
  {{> lambda-permissions}}
  {{/each}}
  {{/each}}
