# This is a templatized verion of a CFo template for Amazon S3 buckets.  This is
# the mango S3 mixin for app deployment.
{{#each buckets}}
{{resourceTitle~}}
MixinS3Bucket:
  Type: "AWS::S3::Bucket"
  DeletionPolicy: Retain
  Properties:
    BucketName: {{name}}
{{/each}}
