# This is a templatized verion of a CFo template for Amazon API Gateway with
# Lambda backends as the handlers.  This template forms the core of every
# Panda Sky app deployment, with mixins adding resources to the description.
#===============================================================================

# Specify the API Gateway
API:
  Type: "AWS::ApiGateway::RestApi"
  Properties:
    Name: {{gatewayName}}
    Description: {{description}}

LambdaRole:
  Type: "AWS::IAM::Role"
  Properties:
    AssumeRolePolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Effect: "Allow"
          Principal:
            Service:
              - lambda.amazonaws.com
          Action:
            - "sts:AssumeRole"
    Policies:
      - PolicyName: {{policyName}}
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "logs:CreateLogGroup"
                - "logs:CreateLogStream"
                - "logs:PutLogEvents"
              Resource: "arn:aws:logs:*:*:*"
            - Effect: Allow
              Action:
                - "s3:*"
              Resource:
                - "arn:aws:s3:::*"

{{#each apiResources}}

{{#unless rootResource}}
{{> resource}}
{{/unless}}

{{> options}}

{{#each methods}}
{{> method gatewayResourceName=../gatewayResourceName rootResource=../rootResource}}
{{/each}} # methods
{{/each}} # apiResources

{{#each schema}}
{{> model }}
{{/each}}

Deployment:
  DependsOn:
  {{#each apiResources}}
  {{#each methods}}
  - {{gatewayMethodName}}
  {{/each}}
  - {{name}}OptionsMethod
  {{/each}}
  Type: "AWS::ApiGateway::Deployment"
  Properties:
    Description:  {{description}} deployment (generated by Panda Sky)
    RestApiId:
      Ref: API
    StageName: {{env}}
    StageDescription:
      Description: {{env}} for {{description}} (generated by Panda Sky)
      StageName: {{env}}
      MethodSettings:
        - ResourcePath: "/"
          HttpMethod: GET
          MetricsEnabled: true
          DataTraceEnabled: false
          #LoggingLevel: INFO  # OFF, ERROR, INFO
          CachingEnabled: false
          # CacheTtlInSeconds: 1800
          # CacheDataEncrypted: false



# Specify CloudFront Distribution, if required.
{{#if aws.cloudfront}}
{{> cloudfront distro="CFRDistro"}}
{{/if}}

{{#if aws.route53}}
{{> route53 distro="CFRDistro"}}
{{/if}}
