# This is a templatized verion of a CFo template for Amazon API Gateway with
# Lambda backends as the handlers.  This template forms the core of every
# Panda Sky app deployment, with mixins adding resources to the description.

# IAM (Identity and Access Management)
{{> iamrole rolename="LambdaRole"}}

## API Gateway

API:
  Type: "AWS::ApiGateway::RestApi"
  Properties:
    Name: {{gatewayName}}
    Description: {{description}}

# The root resource needs different expansion than others.
{{#with rootResource}}
# Define the OPTIONS handler
{{> options}}
# Define all the other methods on the root resource.
{{#each methods}}
{{> method resource=.. }}
{{/each}} # methods
{{/with}}

{{#each skyResources}}
# Define the API Gateway Resource
{{> resource}}
# Define the OPTIONS method
{{> options}}
# Define all the other methods for this resource
{{#each methods}}
{{> method resource=.. }}
{{/each}} # methods
{{/each}} # skyResources

# API Gateway Models
{{#each schema}}
{{> model }}
{{/each}}

# API Gateway Deployment
{{> deployment deployment="Deployment"}}

# CloudFront Distribution
{{#if aws.cloudfront}}
{{> domain distro="CFRDistro"}}
{{/if}}

# DNS
{{#if aws.route53}}
{{> route53 distro="CFRDistro"}}
{{/if}}
