{{name}}OptionsMethod:
  Type: "AWS::ApiGateway::Method"
  Properties:
    RestApiId:
      Ref: API
    ResourceId:
      {{#unless rootResource}}
      Ref: {{gatewayResourceName}}
      {{else}}
      "Fn::GetAtt": ["API", "RootResourceId"]
      {{/unless}}
    AuthorizationType: NONE
    HttpMethod: OPTIONS
    Integration:
      Type: MOCK
      IntegrationResponses:
        - StatusCode: 200
          ResponseParameters:
            "method.response.header.Access-Control-Allow-Headers": "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
            "method.response.header.Access-Control-Allow-Methods": "'{{methodList}}'"
            "method.response.header.Access-Control-Allow-Origin": "'*'"
      RequestTemplates:
        "application/json": "{statusCode: 200}"
    MethodResponses:
      - StatusCode: 200
        ResponseParameters:
          "method.response.header.Access-Control-Allow-Headers": true
          "method.response.header.Access-Control-Allow-Methods": true
          "method.response.header.Access-Control-Allow-Origin": true
