{{roleName}}:
  Type: "AWS::IAM::Role"
  Properties:
    AssumeRolePolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Effect: "Allow"
          Principal:
            Service:
              - lambda.amazonaws.com
          Action:
            - "sts:AssumeRole"
    Policies:
      - PolicyName: {{policyName}}
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          {{#each policyStatements}}
            - Effect: {{Effect}}
              Action:
              {{#each Action}}
                - {{.}}
              {{/each}}
              Resource:
              {{#each Resource}}
                - {{.}}
              {{/each}}
          {{/each}}
