DNSRecords:
  DependsOn:
    - {{distro}}
  Type: "AWS::Route53::RecordSetGroup"
  Properties:
      Comment: "API Gateway deployment for {{name}}-{{env}} -
        Setup by Panda Sky."
      HostedZoneName: {{aws.route53.domain}}
      RecordSets:
        {{#each aws.route53.hostnames}}
        - Name: {{.}}
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2  # CloudFront's HostedZoneId
            DNSName: {"Fn::GetAtt": ["{{../distro}}", "DomainName"]}
        {{/each}}
