{{templateName}}:
  Type: "AWS::ApiGateway::Method"
  Properties:
    RestApiId:
      Ref: API
    {{#if @root.aws.cache.waf}}
    ApiKeyRequired: true
    {{/if}}
    ResourceId:
      "Fn::Select": [ {{resourceIndex}}, {"Fn::Split": [ ",", {"Ref": ResourceIDs} ]}]
    {{#if authorizationType}}
    AuthorizationType: {{authorizationType}}
    {{else}}
    AuthorizationType: NONE
    {{/if}}
    {{#if authorizerId}}
    AuthorizerId: {{authorizerId}}
    {{/if}}
    HttpMethod: {{name}}
    {{#if requestModel}}
    RequestModels:
      "application/json": {{requestModel}}
    {{/if}}
    {{#if parameters}}
    RequestParameters:
    {{#each parameters}}
    {{#if path}}
      "method.request.path.{{name}}": true
    {{else}}
      "method.request.querystring.{{name}}": true
    {{/if}}
    {{/each}}
    {{/if}}
    Integration:
      Type: AWS
      IntegrationHttpMethod: POST
      {{#unless parameters}}
      PassthroughBehavior: WHEN_NO_MATCH
      {{/unless}}
      Uri:
        "Fn::Join":
          - ""
          -
            - "arn:aws:apigateway:"
            - {"Ref": "AWS::Region"}
            - ":lambda:path/2015-03-31/functions/"
            - {{lambda.function.arn}}
            - "/invocations"
      RequestTemplates:
        "application/json": >
          {
            "path": "$context.path",
            "url": {
              "path": {
                #foreach($param in $input.params().path.keySet())
                "$param": "$util.escapeJavaScript($input.params().path.get($param))"
                #if($foreach.hasNext),#end
                #end
              },
              "query": {
                #foreach($param in $input.params().querystring.keySet())
                "$param": "$util.escapeJavaScript($input.params().querystring.get($param))"
                #if($foreach.hasNext),#end
                #end
              }
            },
            "method": "$context.httpMethod",
            "headers": {
              #foreach($param in $input.params().header.keySet())
              #set( $param = $param.toLowerCase() )
              "$param": "$util.escapeJavaScript($input.params().header.get($param))"
              #if($foreach.hasNext),#end
              #end
            },
            "content" : $input.json('$')
          }



      IntegrationResponses:
      {{#each IntegrationResponses}}
        - StatusCode: {{StatusCode}}
        {{#if SelectionPattern}}
          SelectionPattern: {{SelectionPattern}}
        {{/if}}
        {{#if headers}}
          ResponseParameters:
          {{#each headers}}
            method.response.header.{{@key}}: "{{this}}"
          {{/each}}
        {{/if}}

        {{#if ResponseTemplates}}
          ResponseTemplates:
          {{#each ResponseTemplates}}
            {{@key}}: >
              {{indent 14 this}}
          {{/each}}
        {{/if}}

      {{/each}}

    MethodResponses:
    {{#each MethodResponses}}
      - StatusCode: {{StatusCode}}
      {{#if headers}}
        ResponseParameters:
        {{#each headers}}
          method.response.header.{{@key}}: {{this}}
        {{/each}}
      {{/if}}
    {{/each}}
