IAMRole:
  Type: "AWS::IAM::Role"
  Properties:
    AssumeRolePolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Effect: "Allow"
          Principal:
            Service:
              - lambda.amazonaws.com
          Action:
            - "sts:AssumeRole"
    {{#if environment.dispatch.managedPolicies}}
    ManagedPolicyArns:
      {{#each environment.dispatch.managedPolicies}}
      - {{.}}
      {{/each}}
    {{/if}}
    Policies:
      - PolicyName: {{environment.dispatch.name}}
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          {{#each environment.dispatch.policy}}
            - {{indent 14 (yaml .)}}
          {{/each}}
