{{#with lambda}}
{{handler.name}}:
  Type: "AWS::Lambda::Function"
  Properties:
    Description: "Handler for API {{@root.name}}"
    FunctionName: {{function.name}}

    Handler: "lib/sky.API"
    Role:
      "Fn::GetAtt" : ["{{@root.roleName}}", "Arn"]
    Runtime: {{@root.aws.runtime}}
    MemorySize: {{@root.aws.memorySize}}
    Timeout: {{@root.aws.timeout}}
    {{#if @root.aws.vpc}}
    VpcConfig:
      SecurityGroupIds:
        "Fn::Split" : [ ",", {"Ref": SecurityGroups} ]
      SubnetIds:
        "Fn::Split" : [ ",", {"Ref": Subnets} ]
    {{/if}}
    Environment:
      Variables:
      {{#each @root.environmentVariables}}
        {{@key}}: {{this}}
      {{/each}}
    Code:
      S3Bucket: {{handler.bucket}}
      S3Key: "package.zip"
{{/with}}
